# Generated by Django 5.1.4 on 2024-12-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.CharField(max_length=1000),
        ),
    ]
