# Generated by Django 5.1.4 on 2024-12-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
