# Generated by Django 5.1.4 on 2024-12-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
