# Generated by Django 5.1.4 on 2024-12-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_alter_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
