# Generated by Django 5.1.4 on 2024-12-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_product_like_count_remove_product_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
