GET http://127.0.0.1:8000/products HTTP/1.1

# "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1ODE2NzI2LCJpYXQiOjE3MzU4MTU4MjYsImp0aSI6ImM5M2YxZmRjZTVkYjQ1YjQ5ZTgyYjFjYmQ1N2ZmM2M1IiwidXNlcl9pZCI6M30.iVTZmB4ozwRlxlHkzrywbrXLiemrSDcIZIG1m5_WYis"